name: tech_shop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  dio: ^5.4.0
  firebase_auth: ^4.16.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  get: ^4.6.6
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
